[package]
name = "xivhub-market"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.1", features = ["headers"] }
sqlx = { version = "0.6.2", default-features = false, features = ["runtime-tokio-rustls", "sqlite", "macros", "chrono", "offline", "migrate"] }
moka = { version = "0.9.6", features = ["future"] }
color-eyre = "0.6.2"
headers = "0.3.8"
serde = { version = "1.0.148", features = ["derive"] }
serde_json = "1.0.89"
tokio = { version = "1.22.0", features = ["full"] }
validator = { version = "0.16.0", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
dotenvy = "0.15.6"
chrono = "0.4.23"
reqwest = { version = "0.11.13", features = ["json"] }
uuid = "1.2.2"
tower-http = { version = "0.3.5", features = ["full"] }
